apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-call-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: group-call-1
  template:
    metadata:
      labels:
        app: group-call-1
    spec:
      containers:
        - name: group-call-1
          image: group-call-1:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080